# Generated by Django 2.0.1 on 2018-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='accounts\\image\\profile\x0cone-wireless.jpg', upload_to='accounts/image/profile', verbose_name='Profile Image'),
        ),
    ]
