# Generated by Django 2.0.1 on 2018-08-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(help_text='O seu endereço para envio de compra', max_length=80, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=80, verbose_name='Estado')),
                ('pais', models.CharField(max_length=80, verbose_name='Páís')),
                ('cep', models.IntegerField(help_text='Código postal', verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profile\x0cone-wireless.jpg', upload_to='profile', verbose_name='Profile Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Endereco', verbose_name='Endereço'),
        ),
    ]
