# Generated by Django 2.0.1 on 2018-08-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180801_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='endereco',
        ),
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.IntegerField(blank=True, help_text='Código postal', null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='estado',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='user',
            name='logradouro',
            field=models.CharField(blank=True, help_text='O seu endereço para envio de compra', max_length=80, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Páís'),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
