# Generated by Django 2.0.1 on 2018-07-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180726_1134'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caritem',
            unique_together={('cart_key', 'product')},
        ),
    ]
